### ISSUE TITLE
很难找到你的联系方式，所以在这里请教游戏模式V2的原理：）

### ISSUE THREAD

**Issue by zxl777** [jannson/go-stun2#1]
我猜测V2是在服务器开了一个udp转发，让内网的机器暴露在外网，模拟成NAT2的模式。

这样就可以联机了。是不是这样？

我更关心能不能对udp加速？ 服务器在国外，玩家在国内，通过raknet协议通讯。

这种udp底层的游戏通讯协议还有没有可能加速？

**Comment by jannson** [comment]
很抱歉，过了一年才看到你的信息。
至从我的游戏加速之后，出来了好多种不同的加速实现。你说的是对的，就是开了一个 udp 转发来实现 nat2 的模式。中间用什么协议都无所谓。
